name = "GAM"
uuid = "cc454e9f-ce0f-441e-b193-468e31ddef4b"
authors = ["Trent Henderson <trent.henderson1@outlook.com>"]
version = "0.1.0"

[deps]
BSplines = "488c2830-172b-11e9-1591-253b8a7df96d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
